---
#
# SPDX-License-Identifier: GPL-3.0-or-later

default:
  image: "archlinux:latest"

stages:
  - test

.test:
  stage: test
  before_script:
    - pacman --noconfirm -Fy
    - pacman --noconfirm -Syu --needed base-devel git python-tox

linter:
  extends: .test
  script:
    - tox -e linter

coverage:
  extends: .test
  script:
    - tox -e coverage
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: .tox/coverage.xml
      junit: junit-report.xml

docs:
  extends: .test
  script:
    - tox -e docs

integration:
  extends: .test
  script:
    - tox -e integration
